import { ReduxProvider } from "@/app/redux/providers";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <ReduxProvider>
        {children}
      </ReduxProvider>

    </>
  );
}
