export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body>
        {/* Aqui vai apenas o conteúdo da sua aplicação */}
        {children}
      </body>
    </html>
  );
}