export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import montserrat from "@/app/Fonts"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
  )
}
