import ChatBot from "@/app/components/Chatbot/Chat"
import ChatBotButton from "@/app/components/Chatbot/ChatButton"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    {children}
    </>
  )
}
