export const CREATE_NEW_MESSAGE = "CREATE_NEW_MESSAGE";
export const GET_ALL_MESSAGE = "GET_ALL_MESSAGE";
export const SET_UNREAD_COUNTS = "SET_UNREAD_COUNTS";
export const MARK_MESSAGES_AS_READ = "MARK_MESSAGES_AS_READ";