import HeaderAdm from "@/app/components/Header/HeaderAdm"
import Footer from "@/app/components/Footer/Footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
         <>
        <HeaderAdm/>
        {children}
        <Footer/>
        </>

  )
}
