import HeadersAll from "@/app/components/Header/HeadersAll"
import montserrat from "@/app/Fonts"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    {children}
    </>
  )
}
