import HeaderAdm from "@/app/components/Header/HeaderAdm";
import HeadersAll from "@/app/components/Header/HeadersAll";
import montserrat from "@/app/Fonts";
import { jwtDecode } from "jwt-decode";
import { cookies } from "next/headers";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface Usuario {
  // Define your user type based on your JWT structure
  id?: string;
  nome?: string;
  email?: string;
  role?: string;
  // Add other fields you expect in the token
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies(); // Removed await - cookies() is synchronous
  const token = cookieStore.get('token')?.value;
  
  let usuario: Usuario | null = null;

  try {
    if (token) {
      usuario = jwtDecode<Usuario>(token);
    }
  } catch (error) {
    console.error('Failed to decode token:', error);
    // Optionally clear invalid token here
    // cookies().delete('token');
  }

  return (
    <>
      <HeadersAll usuario={usuario} />
      {children}
    </>
  );
}