import HeaderAdm from "@/app/components/Header/HeaderAdm"
import HeadersAll from "@/app/components/Header/HeadersAll"
import montserrat from "@/app/Fonts"
import { jwtDecode } from "jwt-decode"
import { cookies } from "next/headers"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = await cookies();
  const token = cookieStore.get('token')?.value;
  const usuario = jwtDecode(token);

  return (
    
    <>
    <HeadersAll usuario={usuario}/>
    {children}
    </>
  )
}
