import HeaderAdm from "@/app/components/Header/HeaderAdm"
import montserrat from "@/app/Fonts"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      
      <body>
      <HeaderAdm/>

        {children}
        </body>
    </html>
  )
}
